main: net.mattee.mcore.main.mCore
name: mCore
version: 2.0
author: Mattee
api-version: 1.15
commands:
  register:
    description: "Register a new player."
    usage: "/register <password> <password>"
  login:
  mw:
    usage: "/mw <list>"